name: CI tests

on:
  push:
    branches-ignore:
      - master
      - main
      - 'WIP*'

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  build:
    name: Build and test
    needs: validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17.0.1'

      - name: Install dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install libgtk-3-dev

      - name: Run Gradle build
        run: ./gradlew build check
